on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
  schedule:
    - cron: "0 2 * * SUN"

jobs:
  tests:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest, opensuse-latest]

    runs-on: ${{ matrix.os }}
    # runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "install_nim"
        id: install_nim
        uses: iffy/install-nim@v3
      - name: "install_julia"
        id: install_julia
        uses: julia-actions/setup-julia@latest
        with:
          show-versioninfo: 'true'
      - run: nimble install -y
        env:
          JULIA_PATH: ${{ steps.install_julia.outputs.julia-bindir }}/..
      - run: testament r tests/testfull.nim
        env:
          JULIA_PATH: ${{ steps.install_julia.outputs.julia-bindir }}/..
      - run: testament c examples
        env:
          JULIA_PATH: ${{ steps.install_julia.outputs.julia-bindir }}/..
